# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  # create mgmt node
  config.vm.define :mgmt do |mgmt_config|
    mgmt_config.vm.box = "ubuntu/trusty64"
    mgmt_config.vm.hostname = "mgmt"
    mgmt_config.vm.network :private_network, ip: "10.0.15.10"
    mgmt_config.vm.provision :shell, path: "bootstrap-mgmt.sh"
    mgmt_config.vm.provider "virtualbox" do |vb|
      vb.gui = false
      vb.memory = "256"
    end
  end

  config.vm.define :mongo do |mongo_config|
    mongo_config.vm.box = "ubuntu/trusty64"
    mongo_config.vm.hostname = "mongo"
    mongo_config.vm.network "private_network", ip: "10.0.15.20"
    mongo_config.vm.provision :shell, path: "bootstrap-mongo.sh"
    mongo_config.vm.provider "virtualbox" do |vb|
      vb.gui = false
      vb.memory = "256"
    end
  end

  (1..2).each do |i|
    config.vm.define "web#{i}" do |node|
      node.vm.box = "ubuntu/trusty64"
      node.vm.hostname = "web#{i}"
      #node.vm.network "forwarded_port", guest: 80, host: "808#{i}"
      node.vm.network "private_network", ip: "10.0.15.2#{i}"
      node.vm.provision :shell, path: "bootstrap-web.sh"
      node.vm.provider "virtualbox" do |vb|
        vb.gui = false
        vb.memory = "256"
      end
    end
  end

end
